version: "3.8"

services:
  felix-website-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: felix-personal-website-dev
    ports:
      - "3001:4173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      - felix-dev-network

networks:
  felix-dev-network:
    driver: bridge
