services:
  felix-website:
    build: .
    container_name: felix-personal-website
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - felix-network

networks:
  felix-network:
    driver: bridge
